# Generated by Django 3.2.10 on 2022-02-01 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gemsMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaID', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.TextField(max_length=3500)),
            ],
        ),
        migrations.CreateModel(
            name='twitterConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_ref', models.CharField(blank=True, max_length=30, null=True)),
                ('meta_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gems.gemsmeta')),
            ],
        ),
    ]
