# Generated by Django 3.2.10 on 2022-02-03 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsmeta',
            name='svg_image',
            field=models.TextField(default=django.utils.timezone.now, max_length=3500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gemsmeta',
            name='image',
            field=models.ImageField(upload_to='twitterAccounts/', verbose_name='image'),
        ),
    ]
