# Generated by Django 3.2.10 on 2022-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0002_auto_20220203_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemsmeta',
            name='image',
            field=models.ImageField(upload_to='gems/'),
        ),
    ]
