# Generated by Django 3.2.10 on 2022-02-05 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0004_auto_20220203_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsmeta',
            name='image_gem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gems/'),
            preserve_default=False,
        ),
    ]
