# Generated by Django 3.2.10 on 2022-02-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0005_gemsmeta_image_gem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemsmeta',
            name='image',
            field=models.TextField(max_length=35000),
        ),
    ]
