# Generated by Django 3.2.10 on 2022-02-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0006_alter_gemsmeta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemsmeta',
            name='image_gem',
            field=models.FileField(upload_to='gems/'),
        ),
    ]
