# Generated by Django 3.2.10 on 2022-02-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0007_alter_gemsmeta_image_gem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemsmeta',
            name='image_gem',
        ),
        migrations.AlterField(
            model_name='gemsmeta',
            name='image',
            field=models.FileField(upload_to='gems/'),
        ),
    ]
