# Generated by Django 3.2.10 on 2022-02-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0008_auto_20220205_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsmeta',
            name='image_data',
            field=models.CharField(blank=True, max_length=35000, null=True),
        ),
    ]
