# Generated by Django 3.2.10 on 2022-02-06 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0009_gemsmeta_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemsmeta',
            name='image_data',
        ),
        migrations.AddField(
            model_name='gemsmeta',
            name='image_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='gems/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gemsmeta',
            name='image',
            field=models.CharField(blank=True, max_length=35000, null=True),
        ),
    ]
