# Generated by Django 3.2.10 on 2022-02-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0011_twitterconnection_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('oauth_token', models.CharField(max_length=150)),
                ('oauth_secret', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
