# Generated by Django 3.2.10 on 2022-02-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0015_gemsmeta_is_anon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemsmeta',
            name='is_anon',
            field=models.BooleanField(default=True),
        ),
    ]
